"""Dimensionally consistent PSC-IMB-DEM coupling driver.

This script advances the local pebble-bed window with either a quasi-steady
fluid-response exchange or a physically synchronized transient exchange:

1. read the current DEM particle state from LIGGGHTS library mode;
2. update the sparse D3Q19 partially saturated-cell IMB lattice;
3. iterate the LBM solver until the velocity residual reaches tolerance;
4. transfer node-summed hydrodynamic forces and torques to LIGGGHTS;
5. advance DEM by the integer number of substeps satisfying
   ``dt_LBM = n * dt_DEM``.

In ``quasi_steady`` mode each exchange solves the PSC-IMB field to a residual
tolerance before advancing DEM; the exchange count is not a transient physical
clock. In ``transient`` mode each exchange advances an explicit integer number
of LBM lattice steps and DEM advances by the integer number of stable substeps
covering exactly the same physical interval.

The driver is intentionally conservative: skeleton pebbles remain frozen by
the LIGGGHTS input file, fines receive hydrodynamic loads, and every macro-step
records the physical time, LBM convergence, force/torque moving averages, and
contact diagnostics needed for audit.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
from pathlib import Path
import sys
import time
from types import SimpleNamespace

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.run_local_lbm_liggghts_coupled import (  # noqa: E402
    BASE,
    BOX_SIZE,
    apply_si_scaling,
    particles_from_state,
    psc_particles_from_state,
)
from src.lbm_dem.liggghts_contacts import load_liggghts_local_frames, parse_pair_gran_local  # noqa: E402
from src.lbm_dem.liggghts_coupler import LiggghtsForceCoupler  # noqa: E402
from src.lbm_dem.psc3d import SparsePscD3Q19  # noqa: E402


DEFAULT_TEMPLATE = ROOT / "liggghts" / "local_window_fines_coupled.in"
DEFAULT_DATA = (
    "data/production/3d_pebble_bed/local_windows/strong_force_chain/"
    "window_with_fines_packed_slug_900.data"
)
DEFAULT_LOG = ROOT / "coupling_sync" / "synced_coupling_log.csv"

FIELDS = [
    "case_id",
    "seed",
    "data_file",
    "dump_prefix",
    "coupling_mode",
    "use_si_scaling",
    "macro_step",
    "physical_time_s",
    "dt_lbm_s",
    "dt_dem_s",
    "dem_substeps",
    "lbm_iterations",
    "lbm_residual",
    "lbm_converged",
    "imb_momentum_residual",
    "porosity_psc",
    "mean_uz_lu",
    "superficial_uz_lu",
    "n_particles",
    "n_fines",
    "retained_fraction",
    "force_norm_mean_n",
    "force_norm_max_n",
    "torque_norm_mean_nm",
    "torque_norm_max_nm",
    "force_norm_sliding_average_n",
    "torque_norm_sliding_average_nm",
    "n_fine_contacts",
    "n_fine_fine_contacts",
    "max_fine_contact_force_n",
    "psc_force_scale_n_per_lu",
    "psc_torque_scale_nm_per_lu",
    "velocity_lu_per_m_s",
    "angular_lu_per_rad_s",
    "status",
]

FIELD_SCHEMA = {
    "case_id": ("-", "User supplied case identifier for grouping ensemble runs."),
    "seed": ("-", "User supplied seed/index label; blank when the data file is not seed-specific."),
    "data_file": ("path", "LIGGGHTS data file used as the initial DEM state."),
    "dump_prefix": ("-", "Prefix for LIGGGHTS trajectory/contact dump files generated by this run."),
    "coupling_mode": ("-", "quasi_steady or transient."),
    "use_si_scaling": ("0/1", "1 when lattice loads and particle velocities use the helium SI map."),
    "macro_step": ("-", "One synchronized PSC-IMB/DEM exchange step."),
    "physical_time_s": ("s", "End time of the macro step in physical seconds."),
    "dt_lbm_s": ("s", "Transient LBM exchange interval, or DEM exchange interval in quasi-steady mode."),
    "dt_dem_s": ("s", "DEM integration time step written into the temporary LIGGGHTS input."),
    "dem_substeps": ("-", "Integer n satisfying dt_LBM = n*dt_DEM."),
    "lbm_iterations": ("-", "Number of PSC-IMB collide-stream iterations before exchange."),
    "lbm_residual": ("-", "Relative change of mean uz between consecutive PSC-IMB iterations."),
    "lbm_converged": (
        "0/1",
        "1 after a prescribed transient advance, or when a quasi-steady solve reaches its residual threshold.",
    ),
    "imb_momentum_residual": ("lattice units", "Momentum residual reported by the sparse PSC-IMB kernel."),
    "porosity_psc": ("-", "PSC solid-volume porosity estimate on the coupling grid."),
    "mean_uz_lu": ("lu/step", "Mean z velocity from the PSC-IMB lattice."),
    "superficial_uz_lu": ("lu/step", "Void-weighted superficial z velocity on the PSC-IMB lattice."),
    "n_particles": ("-", "Particles currently visible to the DEM state reader."),
    "n_fines": ("-", "Number of particles classified as fines by radius/type inference."),
    "retained_fraction": ("-", "Fraction of fines still inside the local 3-D window after the DEM subcycle."),
    "force_norm_mean_n": ("N", "Mean hydrodynamic force norm transferred to fines."),
    "force_norm_max_n": ("N", "Maximum hydrodynamic force norm transferred to fines."),
    "torque_norm_mean_nm": ("N m", "Mean hydrodynamic torque norm transferred to fines."),
    "torque_norm_max_nm": ("N m", "Maximum hydrodynamic torque norm transferred to fines."),
    "force_norm_sliding_average_n": ("N", "Exponential moving average of force_norm_mean_n, alpha=0.1."),
    "torque_norm_sliding_average_nm": ("N m", "Exponential moving average of torque_norm_mean_nm, alpha=0.1."),
    "n_fine_contacts": ("-", "Contacts in the latest local dump involving at least one fine atom id."),
    "n_fine_fine_contacts": ("-", "Contacts in the latest local dump involving two fine atom ids."),
    "max_fine_contact_force_n": ("N", "Maximum contact force magnitude among contacts involving a fine."),
    "psc_force_scale_n_per_lu": ("N/lu", "Scale applied to lattice hydrodynamic force before passing to DEM."),
    "psc_torque_scale_nm_per_lu": ("N m/lu", "Scale applied to lattice hydrodynamic torque before passing to DEM."),
    "velocity_lu_per_m_s": ("lu/(m/s)", "Scale used to feed DEM translational velocity into PSC-IMB."),
    "angular_lu_per_rad_s": ("lu/(rad/s)", "Scale used to feed DEM angular velocity into PSC-IMB."),
    "status": ("-", "ok, lbm_not_converged, or dry_run_schedule."),
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--case-id", default="synced_psc_imb_dem")
    parser.add_argument("--seed", default="")
    parser.add_argument("--template", type=Path, default=DEFAULT_TEMPLATE)
    parser.add_argument("--data-file", default=DEFAULT_DATA)
    parser.add_argument("--dump-prefix", default="synced_psc")
    parser.add_argument("--T-total", "--T_total", "--total-time", dest="total_time", type=float, default=1.0e-5)
    parser.add_argument("--dt-LBM", "--dt_LBM", "--dt-lbm", dest="dt_lbm", type=float, default=2.0e-7)
    parser.add_argument("--dt-DEM", "--dt_DEM", "--dt-dem", dest="dt_dem", type=float, default=None)
    parser.add_argument("--dt-dem-max", type=float, default=1.2e-9, help="Maximum stable DEM step used by transient auto-subcycling.")
    parser.add_argument("--auto-subcycles", type=int, default=4)
    parser.add_argument("--coupling-mode", choices=("quasi_steady", "transient"), default="quasi_steady")
    parser.add_argument("--lbm-steps-per-exchange", type=int, default=1)
    parser.add_argument("--resolution", type=int, default=40)
    parser.add_argument("--tau", type=float, default=0.72)
    parser.add_argument("--force-z", type=float, default=2.0e-7)
    parser.add_argument(
        "--body-acceleration-z",
        type=float,
        default=None,
        help="Physical body acceleration in m/s^2; required for transient mode and converted to lattice units.",
    )
    parser.add_argument("--psc-subsamples", type=int, default=2)
    parser.add_argument("--psc-min-steps", type=int, default=20)
    parser.add_argument("--psc-max-steps", type=int, default=2000)
    parser.add_argument("--youngs-modulus", type=float, default=9.0e10)
    parser.add_argument("--lbm-residual-threshold", "--residual-tol", dest="residual_tol", type=float, default=1.0e-8)
    parser.add_argument("--apply-psc-torque", action="store_true")
    parser.add_argument("--use-si-scaling", action="store_true")
    parser.add_argument(
        "--allow-unscaled-regression",
        action="store_true",
        help="Permit lattice loads to enter DEM without SI conversion. For code regression only.",
    )
    parser.add_argument("--temperature-k", type=float, default=773.15)
    parser.add_argument("--pressure-pa", type=float, default=2.0e5)
    parser.add_argument("--mu-he", type=float, default=3.7e-5)
    parser.add_argument("--psc-force-scale", type=float, default=1.0)
    parser.add_argument("--psc-torque-scale", type=float, default=1.0)
    parser.add_argument("--velocity-lu-scale", type=float, default=0.0)
    parser.add_argument("--angular-lu-scale", type=float, default=0.0)
    parser.add_argument("--velocity-feedback-factor", type=float, default=1.0)
    parser.add_argument("--angular-feedback-factor", type=float, default=1.0)
    parser.add_argument("--output-csv", "--output", dest="output_csv", type=Path, default=DEFAULT_LOG)
    parser.add_argument("--schema-csv", type=Path, default=None, help="Optional path for the CSV field dictionary.")
    parser.add_argument("--metadata-json", type=Path, default=None, help="Optional path for run metadata.")
    parser.add_argument("--checkpoint-dir", type=Path, default=None, help="Directory for per-macro LIGGGHTS write_data checkpoints.")
    parser.add_argument("--checkpoint-every", type=int, default=1, help="Write a DEM checkpoint every N macro steps; 0 disables checkpoints.")
    parser.add_argument(
        "--stop-when-retained-below",
        type=float,
        default=-1.0,
        help=(
            "Optional early stop for long local-window migration screens. "
            "If non-negative, stop after writing a macro row when retained_fraction "
            "is less than or equal to this threshold."
        ),
    )
    parser.add_argument(
        "--min-macro-before-stop",
        type=int,
        default=1,
        help="Minimum number of macro exchanges before --stop-when-retained-below can trigger.",
    )
    parser.add_argument("--resume", action="store_true", help="Resume from the latest complete CSV row and matching DEM checkpoint.")
    parser.add_argument("--dry-run", action="store_true", help="Only write the integer time-step schedule.")
    return parser.parse_args()


def rel(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(ROOT))
    except ValueError:
        return str(path)


def dem_substeps(args: argparse.Namespace) -> tuple[float, int]:
    if args.coupling_mode == "transient" and args.dt_dem is None:
        if args.dt_dem_max <= 0.0:
            raise ValueError("--dt-dem-max must be positive")
        n = int(math.ceil(args.dt_lbm / args.dt_dem_max))
        return args.dt_lbm / n, n
    if args.dt_dem is None:
        if args.auto_subcycles <= 0:
            raise ValueError("--auto-subcycles must be positive when --dt-DEM is omitted")
        return args.dt_lbm / args.auto_subcycles, args.auto_subcycles
    ratio = args.dt_lbm / args.dt_dem
    n = int(round(ratio))
    if n <= 0 or abs(ratio - n) > 1.0e-10:
        raise ValueError(f"dt_LBM must equal n*dt_DEM; got ratio={ratio:.16g}")
    return args.dt_dem, n


def write_synced_input(template: Path, data_file: str, dump_prefix: str, dt_dem: float, youngs_modulus: float) -> Path:
    BASE.mkdir(parents=True, exist_ok=True)
    dump_base = BASE.relative_to(ROOT)
    lines: list[str] = []
    inserted_hard_particles = False
    for raw in template.read_text().splitlines():
        line = raw.strip()
        if line.startswith("read_data "):
            lines.append(f"read_data {data_file}")
        elif line.startswith("fix m1 all property/global youngsModulus"):
            if youngs_modulus > 1.0e9 and not inserted_hard_particles:
                lines.append("hard_particles yes")
                inserted_hard_particles = True
            lines.append(
                "fix m1 all property/global youngsModulus peratomtype "
                f"{youngs_modulus:.8e} {youngs_modulus:.8e}"
            )
        elif line.startswith("timestep "):
            lines.append(f"timestep {dt_dem:.16e}")
        elif line.startswith("dump traj all custom"):
            lines.append(
                "dump traj all custom 100 "
                f"{dump_base / (dump_prefix + '_traj_*.dump')} "
                "id type x y z vx vy vz fx fy fz radius c_contacts"
            )
        elif line.startswith("dump dlocal all local"):
            lines.append(
                "dump dlocal all local 100 "
                f"{dump_base / (dump_prefix + '_contact_*.local')} "
                "c_cpgl[1] c_cpgl[2] c_cpgl[3] c_cpgl[4] c_cpgl[5] c_cpgl[6] "
                "c_cpgl[7] c_cpgl[8] c_cpgl[9] c_cpgl[10] c_cpgl[11] c_cpgl[12] "
                "c_cpgl[13] c_cpgl[14] c_cpgl[15] c_cpgl[16] c_cpgl[17] c_cpgl[18] c_cpgl[19]"
            )
        else:
            lines.append(raw)
    path = BASE / f"{dump_prefix}_synced.in"
    path.write_text("\n".join(lines) + "\n")
    return path


def solver_particles(state, args: argparse.Namespace):
    return psc_particles_from_state(
        state,
        args.resolution,
        args.velocity_lu_scale * args.velocity_feedback_factor,
        args.angular_lu_scale * args.angular_feedback_factor,
    )


def lbm_converge(solver: SparsePscD3Q19, args: argparse.Namespace) -> tuple[int, float, bool, dict[str, float]]:
    previous = None
    residual = math.inf
    diag: dict[str, float] = {}
    for iteration in range(1, args.psc_max_steps + 1):
        diag = solver.collide_stream_psc()
        current = float(diag.get("mean_uz", 0.0))
        if previous is not None:
            residual = abs(current - previous) / max(abs(current), 1.0e-30)
        previous = current
        if iteration >= args.psc_min_steps and residual < args.residual_tol:
            return iteration, residual, True, diag
    return args.psc_max_steps, residual, False, diag


def lbm_transient_advance(
    solver: SparsePscD3Q19, args: argparse.Namespace
) -> tuple[int, float, bool, dict[str, float]]:
    """Advance an explicit number of physical LBM steps without steady iteration."""

    previous = float(np.mean(solver.uz))
    diag: dict[str, float] = {}
    for _ in range(args.lbm_steps_per_exchange):
        diag = solver.collide_stream_psc()
    current = float(diag.get("mean_uz", previous))
    residual = abs(current - previous) / max(abs(current), 1.0e-30)
    return args.lbm_steps_per_exchange, residual, True, diag


def empty_schedule_rows(args: argparse.Namespace, dt_dem: float, n_dem: int) -> list[dict[str, object]]:
    n_macro = int(math.ceil(args.total_time / args.dt_lbm))
    return [
        {
            "case_id": args.case_id,
            "seed": args.seed,
            "data_file": args.data_file,
            "dump_prefix": args.dump_prefix,
            "coupling_mode": args.coupling_mode,
            "use_si_scaling": int(args.use_si_scaling),
            "macro_step": i + 1,
            "physical_time_s": min((i + 1) * args.dt_lbm, args.total_time),
            "dt_lbm_s": args.dt_lbm,
            "dt_dem_s": dt_dem,
            "dem_substeps": n_dem,
            "lbm_iterations": "",
            "lbm_residual": "",
            "lbm_converged": "",
            "imb_momentum_residual": "",
            "porosity_psc": "",
            "mean_uz_lu": "",
            "superficial_uz_lu": "",
            "n_particles": "",
            "n_fines": "",
            "retained_fraction": "",
            "force_norm_mean_n": "",
            "force_norm_max_n": "",
            "torque_norm_mean_nm": "",
            "torque_norm_max_nm": "",
            "force_norm_sliding_average_n": "",
            "torque_norm_sliding_average_nm": "",
            "n_fine_contacts": "",
            "n_fine_fine_contacts": "",
            "max_fine_contact_force_n": "",
            "psc_force_scale_n_per_lu": "",
            "psc_torque_scale_nm_per_lu": "",
            "velocity_lu_per_m_s": "",
            "angular_lu_per_rad_s": "",
            "status": "dry_run_schedule",
        }
        for i in range(n_macro)
    ]


def write_rows(path: Path, rows: list[dict[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=FIELDS)
        writer.writeheader()
        writer.writerows(rows)


def read_existing_rows(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open(newline="") as fh:
        reader = csv.DictReader(fh)
        if reader.fieldnames != FIELDS:
            raise ValueError(f"Cannot resume {path}: CSV fields do not match current schema")
        return list(reader)


def write_schema(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as fh:
        writer = csv.writer(fh)
        writer.writerow(["field", "unit", "description"])
        for field in FIELDS:
            unit, description = FIELD_SCHEMA.get(field, ("", ""))
            writer.writerow([field, unit, description])


def contact_snapshot_for_fines(prefix: str, fine_ids: set[int]) -> tuple[float, float, float]:
    files = sorted(BASE.glob(f"{prefix}_contact_*.local"))
    if not files or not fine_ids:
        return 0.0, 0.0, 0.0
    frames = load_liggghts_local_frames(files[-1])
    if not frames:
        return 0.0, 0.0, 0.0
    contacts = parse_pair_gran_local(frames[-1])
    if not len(contacts.overlap):
        return 0.0, 0.0, 0.0
    fine_i = np.array([int(atom_id) in fine_ids for atom_id in contacts.ids[:, 0]], dtype=bool)
    fine_j = np.array([int(atom_id) in fine_ids for atom_id in contacts.ids[:, 1]], dtype=bool)
    fine_contact = fine_i | fine_j
    fine_fine = fine_i & fine_j
    max_force = float(np.max(contacts.force_magnitude[fine_contact])) if np.any(fine_contact) else 0.0
    return float(np.sum(fine_contact)), float(np.sum(fine_fine)), max_force


def retained_fraction_by_id(state_after, fine_ids: set[int]) -> float:
    """Fraction of the original fine IDs still inside the local box.

    LIGGGHTS may remove particles that leave a non-periodic local window.  The
    post-DEM state can therefore contain fewer atoms than the pre-DEM state, so
    retention must be computed by atom id rather than by reusing a stale boolean
    mask.
    """

    if not fine_ids:
        return 0.0
    visible = {int(atom_id): idx for idx, atom_id in enumerate(state_after.ids)}
    retained = 0
    for atom_id in fine_ids:
        idx = visible.get(atom_id)
        if idx is None:
            continue
        z = float(state_after.x[idx, 2])
        if 0.0 < z < BOX_SIZE:
            retained += 1
    return retained / float(len(fine_ids))


def checkpoint_dir_for(args: argparse.Namespace) -> Path:
    if args.checkpoint_dir is not None:
        return args.checkpoint_dir
    return args.output_csv.with_name(args.output_csv.stem + "_checkpoints")


def checkpoint_path(args: argparse.Namespace, macro_step: int) -> Path:
    return checkpoint_dir_for(args) / f"{args.dump_prefix}_macro_{macro_step:06d}.data"


def checkpoint_step_from_path(path: Path, dump_prefix: str) -> int | None:
    prefix = f"{dump_prefix}_macro_"
    if not path.name.startswith(prefix) or not path.name.endswith(".data"):
        return None
    raw = path.name[len(prefix) : -len(".data")]
    try:
        return int(raw)
    except ValueError:
        return None


def latest_available_checkpoint(args: argparse.Namespace, max_macro: int) -> tuple[int, Path] | None:
    checkpoints: list[tuple[int, Path]] = []
    checkpoint_dir = checkpoint_dir_for(args)
    if not checkpoint_dir.exists():
        return None
    for path in checkpoint_dir.glob(f"{args.dump_prefix}_macro_*.data"):
        step = checkpoint_step_from_path(path, args.dump_prefix)
        if step is not None and step <= max_macro:
            checkpoints.append((step, path))
    if not checkpoints:
        return None
    return max(checkpoints, key=lambda item: item[0])


def rel_for_liggghts(path: Path) -> str:
    try:
        return path.resolve().relative_to(ROOT).as_posix()
    except ValueError:
        return str(path.resolve())


def resume_state(args: argparse.Namespace, n_macro: int) -> tuple[list[dict[str, str]], int, str | None]:
    if not args.resume:
        return [], 0, None
    rows = read_existing_rows(args.output_csv)
    if not rows:
        return [], 0, None
    complete_rows = [row for row in rows if row.get("status") == "ok"]
    if len(complete_rows) != len(rows):
        raise ValueError(f"Cannot resume {args.output_csv}: non-ok rows are present")
    start_macro = len(rows)
    if start_macro >= n_macro:
        print(f"{args.output_csv} already has {start_macro}/{n_macro} complete rows")
        return rows, start_macro, None
    last_checkpoint = checkpoint_path(args, start_macro)
    if not last_checkpoint.exists():
        fallback = latest_available_checkpoint(args, start_macro)
        if fallback is None:
            raise FileNotFoundError(
                f"Cannot resume after macro {start_macro}: missing checkpoint {last_checkpoint}. "
                "Re-run without --resume or start from an older backed-up checkpoint."
            )
        fallback_macro, fallback_checkpoint = fallback
        if fallback_macro <= 0:
            raise FileNotFoundError(
                f"Cannot resume after macro {start_macro}: no positive checkpoint found in "
                f"{checkpoint_dir_for(args)}"
            )
        print(
            f"Cannot resume after macro {start_macro}: missing checkpoint {last_checkpoint}. "
            f"Falling back to macro {fallback_macro} checkpoint {fallback_checkpoint}."
        )
        rows = rows[:fallback_macro]
        write_rows(args.output_csv, rows)
        start_macro = fallback_macro
        last_checkpoint = fallback_checkpoint
    return rows, start_macro, rel_for_liggghts(last_checkpoint)


def main() -> None:
    args = parse_args()
    if args.total_time <= 0.0 or args.dt_lbm <= 0.0:
        raise ValueError("--T-total and --dt-LBM must be positive")
    if args.lbm_steps_per_exchange <= 0:
        raise ValueError("--lbm-steps-per-exchange must be positive")
    if not args.template.exists():
        raise FileNotFoundError(args.template)
    data_path = ROOT / args.data_file if not Path(args.data_file).is_absolute() else Path(args.data_file)
    wall_start = time.time()

    scale_args = SimpleNamespace(**vars(args))
    scale_info = apply_si_scaling(scale_args)
    for key in ("psc_force_scale", "psc_torque_scale", "velocity_lu_scale", "angular_lu_scale"):
        setattr(args, key, getattr(scale_args, key))
    if not args.use_si_scaling and not args.allow_unscaled_regression:
        raise ValueError(
            "Production PSC-IMB-DEM runs require --use-si-scaling. "
            "Use --allow-unscaled-regression only for explicitly labelled numerical regression cases."
        )
    if args.coupling_mode == "transient":
        if not args.use_si_scaling:
            raise ValueError("Transient coupling requires --use-si-scaling")
        if args.body_acceleration_z is None:
            raise ValueError("Transient coupling requires --body-acceleration-z in physical m/s^2")
        lattice_dt = float(scale_info["dt_s"])
        args.dt_lbm = lattice_dt * args.lbm_steps_per_exchange
        args.force_z = args.body_acceleration_z * lattice_dt * lattice_dt / float(scale_info["dx_m"])
        ratio_total = args.total_time / args.dt_lbm
        if abs(ratio_total - round(ratio_total)) > 1.0e-10:
            raise ValueError(
                "Transient --T-total must be an integer multiple of the physical LBM exchange interval "
                f"{args.dt_lbm:.16e} s; got ratio={ratio_total:.16g}"
            )

    dt_dem, n_dem = dem_substeps(args)
    n_macro = int(math.ceil(args.total_time / args.dt_lbm))

    if args.dry_run:
        rows = empty_schedule_rows(args, dt_dem, n_dem)
        write_rows(args.output_csv, rows)
        write_schema(args.schema_csv or args.output_csv.with_name(args.output_csv.stem + "_schema.csv"))
        print(f"dt_LBM/dt_DEM={n_dem}; wrote {args.output_csv}")
        return

    if not data_path.exists():
        raise FileNotFoundError(data_path)

    rows, start_macro, resume_data_file = resume_state(args, n_macro)
    if start_macro >= n_macro:
        return
    input_data_file = resume_data_file or args.data_file
    if start_macro == 0:
        for pattern in (f"{args.dump_prefix}_traj_*.dump", f"{args.dump_prefix}_contact_*.local"):
            for old in BASE.glob(pattern):
                old.unlink()
    case_input = write_synced_input(args.template, input_data_file, args.dump_prefix, dt_dem, args.youngs_modulus)

    if rows:
        force_ma = float(rows[-1].get("force_norm_sliding_average_n", 0.0) or 0.0)
        torque_ma = float(rows[-1].get("torque_norm_sliding_average_nm", 0.0) or 0.0)
    else:
        force_ma = 0.0
        torque_ma = 0.0
    alpha_ma = 0.1
    early_stop_triggered = False
    early_stop_reason = ""
    solver: SparsePscD3Q19 | None = None

    with LiggghtsForceCoupler(case_input, quiet=True) as dem:
        for macro in range(start_macro, n_macro):
            state = dem.state()
            particle_table = particles_from_state(state)
            fine_mask = particle_table[:, 1] == 2
            fine_ids = {int(atom_id) for atom_id in particle_table[fine_mask, 0]}
            particles = solver_particles(state, args)
            if solver is None:
                solver = SparsePscD3Q19(
                    n=args.resolution,
                    particles=particles,
                    tau=args.tau,
                    subsamples=args.psc_subsamples,
                    body_force_z=args.force_z,
                )
            else:
                solver.particles = particles
                if solver.hydro_forces.shape[0] != len(particles):
                    solver.hydro_forces = np.zeros((len(particles), 3), dtype=float)
                    solver.hydro_torques = np.zeros((len(particles), 3), dtype=float)

            if args.coupling_mode == "transient":
                lbm_iters, lbm_residual, converged, diag = lbm_transient_advance(solver, args)
            else:
                lbm_iters, lbm_residual, converged, diag = lbm_converge(solver, args)
            forces = args.psc_force_scale * solver.hydro_forces
            torques = args.psc_torque_scale * solver.hydro_torques
            forces[~fine_mask] = 0.0
            torques[~fine_mask] = 0.0
            dem.set_dragforces(state.ids, forces)
            if args.apply_psc_torque:
                dem.set_hdtorques(state.ids, torques)
            dem.run(n_dem)
            state_after = dem.state()

            f_norm = np.linalg.norm(forces[fine_mask], axis=1) if np.any(fine_mask) else np.zeros(0)
            t_norm = np.linalg.norm(torques[fine_mask], axis=1) if np.any(fine_mask) else np.zeros(0)
            force_mean = float(np.mean(f_norm)) if len(f_norm) else 0.0
            torque_mean = float(np.mean(t_norm)) if len(t_norm) else 0.0
            force_ma = (1.0 - alpha_ma) * force_ma + alpha_ma * force_mean
            torque_ma = (1.0 - alpha_ma) * torque_ma + alpha_ma * torque_mean
            retained = retained_fraction_by_id(state_after, fine_ids)
            n_fine_contacts, n_fine_fine, max_fine_force = contact_snapshot_for_fines(args.dump_prefix, fine_ids)
            porosity = 1.0 - float(diag.get("solid_volume_lu", 0.0)) / float(args.resolution**3)
            row = {
                "case_id": args.case_id,
                "seed": args.seed,
                "data_file": args.data_file,
                "dump_prefix": args.dump_prefix,
                "coupling_mode": args.coupling_mode,
                "use_si_scaling": int(args.use_si_scaling),
                "macro_step": macro + 1,
                "physical_time_s": min((macro + 1) * args.dt_lbm, args.total_time),
                "dt_lbm_s": args.dt_lbm,
                "dt_dem_s": dt_dem,
                "dem_substeps": n_dem,
                "lbm_iterations": lbm_iters,
                "lbm_residual": lbm_residual,
                "lbm_converged": int(converged),
                "imb_momentum_residual": float(diag.get("momentum_residual", math.nan)),
                "porosity_psc": porosity,
                "mean_uz_lu": float(diag.get("mean_uz", math.nan)),
                "superficial_uz_lu": float(np.mean(solver.uz * (1.0 - np.clip(solver.solid, 0.0, 1.0)))),
                "n_particles": len(particles),
                "n_fines": int(np.sum(fine_mask)),
                "retained_fraction": retained,
                "force_norm_mean_n": force_mean,
                "force_norm_max_n": float(np.max(f_norm)) if len(f_norm) else 0.0,
                "torque_norm_mean_nm": torque_mean,
                "torque_norm_max_nm": float(np.max(t_norm)) if len(t_norm) else 0.0,
                "force_norm_sliding_average_n": force_ma,
                "torque_norm_sliding_average_nm": torque_ma,
                "n_fine_contacts": n_fine_contacts,
                "n_fine_fine_contacts": n_fine_fine,
                "max_fine_contact_force_n": max_fine_force,
                "psc_force_scale_n_per_lu": args.psc_force_scale,
                "psc_torque_scale_nm_per_lu": args.psc_torque_scale,
                "velocity_lu_per_m_s": args.velocity_lu_scale,
                "angular_lu_per_rad_s": args.angular_lu_scale,
                "status": "ok" if converged else "lbm_not_converged",
            }
            rows.append(row)
            if args.checkpoint_every > 0 and (macro + 1) % args.checkpoint_every == 0:
                dem.write_data(checkpoint_path(args, macro + 1))
            write_rows(args.output_csv, rows)
            write_schema(args.schema_csv or args.output_csv.with_name(args.output_csv.stem + "_schema.csv"))
            print(
                f"macro={macro + 1:04d}/{n_macro} t={row['physical_time_s']:.3e}s "
                f"sub={n_dem} lbm_it={lbm_iters} res={lbm_residual:.2e} "
                f"retained={retained:.3f} fine_contacts={n_fine_contacts:.0f}"
            )
            if (
                args.stop_when_retained_below >= 0.0
                and (macro + 1) >= args.min_macro_before_stop
                and retained <= args.stop_when_retained_below
            ):
                early_stop_triggered = True
                early_stop_reason = (
                    f"retained_fraction {retained:.6g} <= "
                    f"{args.stop_when_retained_below:.6g}"
                )
                print(
                    "early stop: all relevant fines have left the local statistics "
                    f"window ({early_stop_reason})"
                )
                break

    scale_csv = args.output_csv.with_name(args.output_csv.stem + "_scales.csv")
    with scale_csv.open("w", newline="") as fh:
        writer = csv.writer(fh)
        writer.writerow(["quantity", "value"])
        for key, value in scale_info.items():
            writer.writerow([key, value])
        writer.writerow(["case_input", rel(case_input)])
        writer.writerow(["youngs_modulus_pa", args.youngs_modulus])
        writer.writerow(["case_id", args.case_id])
        writer.writerow(["seed", args.seed])
        writer.writerow(["data_file", args.data_file])
    metadata_path = args.metadata_json or args.output_csv.with_name(args.output_csv.stem + "_metadata.json")
    metadata = {
        "case_id": args.case_id,
        "seed": args.seed,
        "data_file": args.data_file,
        "dump_prefix": args.dump_prefix,
        "template": rel(args.template),
        "generated_liggghts_input": rel(case_input),
        "output_csv": rel(args.output_csv),
        "schema_csv": rel(args.schema_csv or args.output_csv.with_name(args.output_csv.stem + "_schema.csv")),
        "scale_csv": rel(scale_csv),
        "total_time_s": args.total_time,
        "dt_lbm_s": args.dt_lbm,
        "dt_dem_s": dt_dem,
        "dem_substeps": n_dem,
        "macro_steps_requested": n_macro,
        "macro_steps_completed": len(rows),
        "early_stop_triggered": early_stop_triggered,
        "early_stop_reason": early_stop_reason,
        "stop_when_retained_below": args.stop_when_retained_below,
        "min_macro_before_stop": args.min_macro_before_stop,
        "resolution": args.resolution,
        "tau": args.tau,
        "force_z": args.force_z,
        "residual_tol": args.residual_tol,
        "psc_min_steps": args.psc_min_steps,
        "psc_max_steps": args.psc_max_steps,
        "youngs_modulus_pa": args.youngs_modulus,
        "apply_psc_torque": args.apply_psc_torque,
        "use_si_scaling": args.use_si_scaling,
        "coupling_regime": args.coupling_mode,
        "physical_time_basis": (
            "explicit_lbm_and_dem_transient_time"
            if args.coupling_mode == "transient"
            else "dem_exchange_time_with_quasi_steady_fluid_response"
        ),
        "dem_exchange_time_s": args.dt_lbm,
        "lbm_lattice_time_scale_s": scale_info["dt_s"],
        "lbm_steps_per_exchange": args.lbm_steps_per_exchange,
        "body_acceleration_z_m_s2": args.body_acceleration_z,
        "unscaled_regression_only": bool(args.allow_unscaled_regression and not args.use_si_scaling),
        "wall_time_s": time.time() - wall_start,
        "scale_info": scale_info,
    }
    metadata_path.parent.mkdir(parents=True, exist_ok=True)
    metadata_path.write_text(json.dumps(metadata, indent=2, sort_keys=True) + "\n")
    print(f"wrote {args.output_csv}")
    print(f"wrote {scale_csv}")
    print(f"wrote {metadata_path}")


if __name__ == "__main__":
    main()
